EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EleWise.ELMA.Extensions;
using EleWise.ELMA.Web.Mvc.Extensions;
using EleWise.ELMA.Web.Mvc.Attributes;
using EleWise.ELMA.Web.Mvc.Controllers;
using Orchard;
using Orchard.Themes;

namespace EleWise.ELMA.MailSniffer.Web.Controllers
{
    [Themed]
    public class HomeController : BaseController
    {
        //
        // GET: /EleWise.ELMA.MailSniffer.Web/

        public ActionResult Index()
        {
            return View();
        }

    }
}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Controllers/IncidentController.cs
using EleWise.ELMA.BPM.Mvc.Controllers;
using EleWise.ELMA.Common.Managers;
using EleWise.ELMA.MailSniffer.Services;
using EleWise.ELMA.MailSniffer.Models;
using EleWise.ELMA.Messages.Models;
using EleWise.ELMA.Model.Managers;
using EleWise.ELMA.Model.Services;
using EleWise.ELMA.Security;
using EleWise.ELMA.Security.Managers;
using EleWise.ELMA.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EleWise.ELMA.MailSniffer.Web.Controllers
{
    public class IncidentController : BPMController
    {
        public IncidentService IncidentService { get; set; }

        /// <summary>
        /// Отправить сообщение об инциденте ответственным
        /// </summary>
        /// <param name="incidentId"></param>
        /// <returns></returns>
        public bool SendMessage(long incidentId)
        {
            IncidentService.CreateMessage(incidentId);
            return true;
        }

    }
}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Controllers/MailSnifferSettingController.cs
using EleWise.ELMA.BPM.Mvc.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EleWise.ELMA.MailSniffer.Web.Controllers
{
    public class MailSnifferSettingController : BPMController
    {
        public MailSnifferSettingsModule SettingsModule { get; set; }

        public MailSnifferSettings Settings
        {
            get
            {
                return SettingsModule.Settings;
            }
        }

        [HttpGet]
        public ActionResult RenderDisplay()
        {
            return PartialView(Settings);
        }

        [HttpGet]
        public ActionResult RenderEdit()
        {
            return PartialView(Settings);
        }
    }
}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Controllers/MailSnifferSettingsModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EleWise.ELMA.ComponentModel;
using EleWise.ELMA.Web.Mvc.Models.Settings;
using System.Web.Mvc.Html;

namespace EleWise.ELMA.MailSniffer.Web.Controllers
{
    [Component(Order = 261)]
    public class MailSnifferSettingsModuleController : GlobalSettingsModuleControllerBase<MailSnifferSettings, MailSnifferSettingsModule>
    {
        public MailSnifferSettingsModuleController(MailSnifferSettingsModule module) 
            : base(module)
        {
        }

        public override MvcHtmlString RenderDisplay(HtmlHelper html)
        {
            return html.Action("RenderDisplay", "MailSnifferSetting", new { area = RouteProvider.AreaName });
        }

        public override MvcHtmlString RenderEdit(HtmlHelper html)
        {
            return html.Action("RenderEdit", "MailSnifferSetting", new { area = RouteProvider.AreaName });
        }
    }
}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "EleWise.ELMA.MailSniffer.Web";
}

<h2>Welcome to ELMA 3 modules development</h2>

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Views/Shared/Incident/SendMessage.cshtml
@model IIncident

@using EleWise.ELMA.MailSniffer.Models
@using EleWise.ELMA.Services
@using EleWise.ELMA.MailSniffer.API.Service
@using EleWise.ELMA.MailSniffer.API.Models
@using EleWise.ELMA.MailSniffer.Services

<script>
    function SendMessage(id) {
        $.ajax({
            url: '@Url.Action("SendMessage", "Incident", new {area = "EleWise.ELMA.MailSniffer.Web" })',
            dataType: 'json',
            type: 'post',
            data: ({ incidentId: id}),
            success: function(data) {
                jAlert("@SR.T("Статус отправки сообщения: ")" + data);
            }
        });
    }
</script>

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Views/Shared/MailSnifferSetting/RenderDisplay.cshtml
@using EleWise.ELMA.BPM.Web.Common.Mvc.html
@using EleWise.ELMA.BPM.Web.Common.Models
@using EleWise.ELMA.Model.Types.Settings
@model EleWise.ELMA.MailSniffer.MailSnifferSettings

@using (Html.TableForm(v => v.ViewType(EleWise.ELMA.Model.Views.ViewType.Display).Attributes(a => a.@class = "settings_table")))
{
    @Html.Property(m => m.NotifyUsers)
    @Html.Property(m => m.ExceptionUsers)
    @Html.Property(m => m.TrialDuration)
    @Html.Property(m => m.MonitorEmployeesOnProbation)
    @Html.Property(m => m.EmployeesOnProbation, a => a.ReadOnly = true)
    @Html.Property(m => m.MonitorEmployeesOnDismissal)
    @Html.Property(m => m.EmployeesOnDismissal, a => a.ReadOnly = true)
    @Html.Property(m => m.NotifyEmployees)
    @Html.Property(m => m.FilterList, a =>
                        {
                            a.ShowDescription = true;
                            a.TypeSettings = new StringSettings() { MultiLine = true };
                        })
    @Html.Property(m => m.BlockFilterList, a =>
                        {
                            a.ShowDescription = true;
                            a.TypeSettings = new StringSettings() { MultiLine = true };
                        })

}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Views/Shared/MailSnifferSetting/RenderEdit.cshtml
@using EleWise.ELMA.BPM.Web.Common.Mvc.html
@using EleWise.ELMA.BPM.Web.Common.Models
@using EleWise.ELMA.Model.Types.Settings
@model EleWise.ELMA.MailSniffer.MailSnifferSettings

@using (Html.TableForm(v => v.ViewType(EleWise.ELMA.Model.Views.ViewType.Edit).Attributes(a => a.@class = "settings_table")))
{
    @Html.EditableProperty(m => m.NotifyUsers)
    @Html.EditableProperty(m => m.ExceptionUsers)
    @Html.EditableProperty(m => m.TrialDuration)
    @Html.EditableProperty(m => m.MonitorEmployeesOnProbation)
    @Html.Property(m => m.EmployeesOnProbation, a => a.ReadOnly = true)
    @Html.EditableProperty(m => m.MonitorEmployeesOnDismissal)
    @Html.Property(m => m.EmployeesOnDismissal, a => a.ReadOnly = true)
    @Html.EditableProperty(m => m.NotifyEmployees)
    @Html.EditableProperty(m => m.FilterList, a =>
                        {
                            a.ShowDescription = true;
                            a.TypeSettings = new StringSettings() { MultiLine = true };
                        })
    @Html.EditableProperty(m => m.BlockFilterList, a =>
                        {
                            a.ShowDescription = true;
                            a.TypeSettings = new StringSettings() { MultiLine = true };
                        })
}

EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer/EleWise.ELMA.MailSniffer.Web/Views/User/UserProfileInfo.cshtml
@model EditUserModel
@using EleWise.ELMA.BPM.Web.Security.Models
@using EleWise.ELMA.Content.Managers
@using EleWise.ELMA.Content.Models
@using EleWise.ELMA.Security
@using EleWise.ELMA.Services
@using PermissionProvider = EleWise.ELMA.Content.PermissionProvider

@Html.EditableProperty("User.IPAdress")